import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Button, Divider, FormControl, FormLabel, Heading, Input, Text, Avatar, IconButton, VStack, HStack, Icon, Tooltip, Flex, } from '@chakra-ui/react';
import { FiUser, FiMail, FiPhone, FiBriefcase, FiCamera, FiTrash2, FiSave } from 'react-icons/fi';
import { useProfileStyles } from '@/hooks/useProfileStyles';
import { useProfileLogic } from '@/hooks/useProfileLogic';
import { PageHeader } from '@/components/PageHeader';
export default function Perfil() {
    const styles = useProfileStyles();
    const { profile, isLoading, isUploading, fileInputRef, handleInputChange, formatPhoneForDisplay, handleAvatarChange, handleRemoveAvatar, handleSave } = useProfileLogic();
    if (!profile) {
        return (_jsx(Box, { px: 4, children: _jsx(Text, { children: "Carregando..." }) }));
    }
    return (_jsxs(Box, { bg: "inherit", minH: "100vh", children: [_jsx(PageHeader, { title: "Perfil", subtitle: "Gerencie suas informa\u00E7\u00F5es pessoais", icon: FiUser, breadcrumbs: [
                    { label: 'Dashboard', href: '/' },
                    { label: 'Configurações', href: '/configuracoes' },
                    { label: 'Perfil', href: '/configuracoes/profile' },
                ] }), _jsx(Box, { px: { base: 4, xl: 8 }, pb: 12, children: _jsxs(VStack, { spacing: 6, w: "full", align: "stretch", children: [_jsx(Box, { borderWidth: "2px", borderRadius: "lg", p: 6, bg: styles.colors.bg, borderColor: styles.colors.border, w: "full", children: _jsxs(VStack, { spacing: 4, align: "center", children: [_jsxs(Box, { position: "relative", children: [_jsx(Avatar, { size: "xl", src: profile.avatar_url || undefined, name: profile.full_name || profile.email, borderWidth: "2px", borderColor: styles.colors.border }), _jsxs(HStack, { position: "absolute", bottom: "-3", right: "-8", spacing: 1, zIndex: 2, children: [_jsx("input", { type: "file", id: "avatar-input", ref: fileInputRef, onChange: handleAvatarChange, accept: "image/*", style: { display: 'none' } }), _jsx(Tooltip, { label: "Alterar foto", placement: "top", children: _jsx(IconButton, { isLoading: isUploading, as: "div", size: "xs", rounded: "full", colorScheme: "blue", "aria-label": "Alterar foto", icon: _jsx(Icon, { as: FiCamera, fontSize: "0.9rem" }), boxShadow: "base", _hover: {
                                                                transform: 'scale(1.1)',
                                                                boxShadow: 'md',
                                                            }, transition: "all 0.2s", cursor: "pointer", onClick: () => fileInputRef.current?.click() }) }), profile.avatar_url && (_jsx(Tooltip, { label: "Remover foto", placement: "right", children: _jsx(IconButton, { "aria-label": "Remover foto", icon: _jsx(Icon, { as: FiTrash2, fontSize: "0.9rem" }), size: "xs", colorScheme: "red", variant: "solid", rounded: "full", onClick: handleRemoveAvatar, isLoading: isLoading, boxShadow: "base", _hover: {
                                                                transform: 'scale(1.1)',
                                                                boxShadow: 'md',
                                                            }, transition: "all 0.2s" }) }))] })] }), _jsxs(VStack, { spacing: 1, children: [_jsx(Heading, { size: "md", children: profile.full_name || 'Nome não definido' }), _jsx(Text, { color: styles.colors.text, children: profile.email }), profile.role && (_jsxs(HStack, { spacing: 2, bg: styles.colors.roleTag, px: 3, py: 1, rounded: "full", children: [_jsx(Icon, { as: FiUser, color: styles.colors.icon }), _jsx(Text, { fontSize: "sm", color: styles.colors.text, children: profile.role })] }))] })] }) }), _jsxs(Box, { borderWidth: "2px", borderRadius: "lg", p: 6, bg: styles.colors.bg, borderColor: styles.colors.border, w: "full", children: [_jsx(Heading, { size: "md", mb: 4, children: "Informa\u00E7\u00F5es Pessoais" }), _jsx(Divider, { mb: 6, borderColor: styles.colors.border }), _jsxs(VStack, { spacing: 6, align: "stretch", children: [_jsxs(FormControl, { children: [_jsx(FormLabel, { color: styles.colors.label, children: _jsxs(HStack, { spacing: 2, children: [_jsx(Icon, { as: FiUser, color: styles.colors.icon }), _jsx(Text, { children: "Nome Completo" })] }) }), _jsx(Input, { placeholder: "Seu nome completo", value: profile.full_name || '', onChange: (e) => handleInputChange('full_name', e.target.value), bg: styles.colors.input, ...styles.components.input })] }), _jsxs(FormControl, { children: [_jsx(FormLabel, { color: styles.colors.label, children: _jsxs(HStack, { spacing: 2, children: [_jsx(Icon, { as: FiMail, color: styles.colors.icon }), _jsx(Text, { children: "E-mail" })] }) }), _jsx(Input, { value: profile.email, isReadOnly: true, bg: styles.colors.inputReadOnly, opacity: 0.8, cursor: "not-allowed" })] }), _jsxs(FormControl, { children: [_jsx(FormLabel, { color: styles.colors.label, children: _jsxs(HStack, { spacing: 2, children: [_jsx(Icon, { as: FiBriefcase, color: styles.colors.icon }), _jsx(Text, { children: "Cargo" })] }) }), _jsx(Input, { placeholder: "Seu cargo na empresa", value: profile.role || '', onChange: (e) => handleInputChange('role', e.target.value), bg: styles.colors.input, ...styles.components.input })] }), _jsxs(FormControl, { children: [_jsx(FormLabel, { color: styles.colors.label, children: _jsxs(HStack, { spacing: 2, children: [_jsx(Icon, { as: FiPhone, color: styles.colors.icon }), _jsx(Text, { children: "Telefone" })] }) }), _jsx(Input, { type: "tel", value: formatPhoneForDisplay(profile.phone), onChange: (e) => handleInputChange('phone', e.target.value), placeholder: "(00) 00000-0000", bg: styles.colors.input, ...styles.components.input })] })] }), _jsx(Divider, { my: 8, borderColor: styles.colors.border }), _jsx(Flex, { justify: "center", children: _jsx(Button, { colorScheme: "blue", size: "lg", leftIcon: _jsx(Icon, { as: FiSave }), onClick: handleSave, isLoading: isLoading, loadingText: "Salvando...", boxShadow: "base", px: 12, _hover: {
                                            transform: 'translateY(-1px)',
                                            boxShadow: 'md',
                                        }, transition: "all 0.2s", children: "Salvar Altera\u00E7\u00F5es" }) })] })] }) })] }));
}
